name: PyPI
on:
  push:
    branches:
      - main

jobs:
  build-n-publish:
    name: "Build and publish Python \U0001F40D distributions \U0001F4E6 to PyPI and\
      \ TestPyPI"
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Setup Python
        run: uv python install
      - id: measurement-4
        name: Record Measurement After Setup Python
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Setup Python
          task: get-measurement
      - name: Install the project
        run: 'uv sync --all-extras --dev

          uv pip install -e "."

          '
      - id: measurement-6
        name: Record Measurement After Install the project
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install the project
          task: get-measurement
      - name: Activate the project
        run: source .venv/bin/activate
      - id: measurement-8
        name: Record Measurement After Activate the project
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Activate the project
          task: get-measurement
      - name: Build package
        run: uv build
      - id: measurement-10
        name: Record Measurement After Build package
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Build package
          task: get-measurement
      - name: Check long_description
        run: uv run twine check dist/*
      - id: measurement-12
        name: Record Measurement After Check long_description
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Check long_description
          task: get-measurement
      - if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        name: "Publish distribution \U0001F4E6 to Test PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypitesttoken }}
          repository_url: https://test.pypi.org/legacy/
          user: __token__
      - name: Run tests
        run: uv run pytest src/negmas tests/core || uv run pytest --last-failed src/negmas
          tests/core
      - id: measurement-15
        name: Record Measurement After Run tests
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Run tests
          task: get-measurement
      - if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        name: "Publish distribution \U0001F4E6 to PyPI"
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypiapitoken }}
          user: __token__
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${ steps.final-measurement.outputs.data-total-json }' > total_energy_consumption-1740225772.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-1740225772.json
    timeout-minutes: 60
